"""Option for all select box fields"""

districts_select = """<select name="district">
  <option value="achham" selected>Achham</option>
  <option value="arghakhanchi">Arghakhanchi</option>
  <option value="baglung">Baglung</option>
  <option value="baitadi">Baitadi</option>
  <option value="bajhang">Bajhang</option>
  <option value="bajura">Bajura</option>
  <option value="banke">Banke</option>
  <option value="bara">Bara</option>
  <option value="bardiya">Bardiya</option>
  <option value="bhaktapur">Bhaktapur</option>
  <option value="bhojpur">Bhojpur</option>
  <option value="chitwan">Chitwan</option>
  <option value="dadeldhura">Dadeldhura</option>
  <option value="dailekh">Dailekh</option>
  <option value="dang_deukhuri">Dang Deukhuri</option>
  <option value="darchula">Darchula</option>
  <option value="dhading">Dhading</option>
  <option value="dhankuta">Dhankuta</option>
  <option value="dhanusa">Dhanusa</option>
  <option value="dholkha">Dholkha</option>
  <option value="dolpa">Dolpa</option>
  <option value="doti">Doti</option>
  <option value="gorkha">Gorkha</option>
  <option value="gulmi">Gulmi</option>
  <option value="humla">Humla</option>
  <option value="ilam">Ilam</option>
  <option value="jajarkot">Jajarkot</option>
  <option value="jhapa">Jhapa</option>
  <option value="jumla">Jumla</option>
  <option value="kailali">Kailali</option>
  <option value="kalikot">Kalikot</option>
  <option value="kanchanpur">Kanchanpur</option>
  <option value="kapilvastu">Kapilvastu</option>
  <option value="kaski">Kaski</option>
  <option value="kathmandu">Kathmandu</option>
  <option value="kavrepalanchok">Kavrepalanchok</option>
  <option value="khotang">Khotang</option>
  <option value="lalitpur">Lalitpur</option>
  <option value="lamjung">Lamjung</option>
  <option value="mahottari">Mahottari</option>
  <option value="makwanpur">Makwanpur</option>
  <option value="manang">Manang</option>
  <option value="morang">Morang</option>
  <option value="mugu">Mugu</option>
  <option value="mustang">Mustang</option>
  <option value="myagdi">Myagdi</option>
  <option value="nawalparasi">Nawalparasi</option>
  <option value="nuwakot">Nuwakot</option>
  <option value="okhaldhunga">Okhaldhunga</option>
  <option value="palpa">Palpa</option>
  <option value="panchthar">Panchthar</option>
  <option value="parbat">Parbat</option>
  <option value="parsa">Parsa</option>
  <option value="pyuthan">Pyuthan</option>
  <option value="ramechhap">Ramechhap</option>
  <option value="rasuwa">Rasuwa</option>
  <option value="rautahat">Rautahat</option>
  <option value="rolpa">Rolpa</option>
  <option value="rukum">Rukum</option>
  <option value="rupandehi">Rupandehi</option>
  <option value="salyan">Salyan</option>
  <option value="sankhuwasabha">Sankhuwasabha</option>
  <option value="saptari">Saptari</option>
  <option value="sarlahi">Sarlahi</option>
  <option value="sindhuli">Sindhuli</option>
  <option value="sindhupalchok">Sindhupalchok</option>
  <option value="siraha">Siraha</option>
  <option value="solukhumbu">Solukhumbu</option>
  <option value="sunsari">Sunsari</option>
  <option value="surkhet">Surkhet</option>
  <option value="syangja">Syangja</option>
  <option value="tanahu">Tanahu</option>
  <option value="taplejung">Taplejung</option>
  <option value="terhathum">Terhathum</option>
  <option value="udayapur">Udayapur</option>
</select>"""

provinces_select = """
<select name="province">
  <option value="bagmati" selected>Bagmati</option>
  <option value="gandaki">Gandaki</option>
  <option value="karnali">Karnali</option>
  <option value="lumbini">Lumbini</option>
  <option value="province1">Province 1</option>
  <option value="province2">Province 2</option>
  <option value="sudurpaschim">Sudurpaschim</option>
</select>
"""

zones_select = """
<select name="zone">
  <option value="bagmati">Bagmati</option>
  <option value="bheri">Bheri</option>
  <option value="dhawalagiri">Dhawalagiri</option>
  <option value="dandaki">Gandaki</option>
  <option value="janakpur">Janakpur</option>
  <option value="karnali">Karnali</option>
  <option value="koshi">Koshi</option>
  <option value="lumbini">Lumbini</option>
  <option value="mahakali" selected>Mahakali</option>
  <option value="mechi">Mechi</option>
  <option value="narayani">Narayani</option>
  <option value="rapti">Rapti</option>
  <option value="sagarmatha">Sagarmatha</option>
  <option value="seti">Seti</option>
</select>
"""
