# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161104044749 on 2016-11-05 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.mx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', localflavor.mx.models.MXStateField(max_length=4)),
            ],
        ),
    ]
