from django.utils.translation import ugettext_lazy as _

#: A list of prefectures
JP_PREFECTURES = (
    ('hokkaido', _('Hokkaido'),),
    ('aomori', _('Aomori'),),
    ('iwate', _('Iwate'),),
    ('miyagi', _('Miyagi'),),
    ('akita', _('Akita'),),
    ('yamagata', _('Yamagata'),),
    ('fukushima', _('Fukushima'),),
    ('ibaraki', _('Ibaraki'),),
    ('tochigi', _('Tochigi'),),
    ('gunma', _('Gunma'),),
    ('saitama', _('Saitama'),),
    ('chiba', _('Chiba'),),
    ('tokyo', _('Tokyo'),),
    ('kanagawa', _('Kanagawa'),),
    ('yamanashi', _('Yamanashi'),),
    ('nagano', _('Nagano'),),
    ('niigata', _('Niigata'),),
    ('toyama', _('Toyama'),),
    ('ishikawa', _('Ishikawa'),),
    ('fukui', _('Fukui'),),
    ('gifu', _('Gifu'),),
    ('shizuoka', _('Shizuoka'),),
    ('aichi', _('Aichi'),),
    ('mie', _('Mie'),),
    ('shiga', _('Shiga'),),
    ('kyoto', _('Kyoto'),),
    ('osaka', _('Osaka'),),
    ('hyogo', _('Hyogo'),),
    ('nara', _('Nara'),),
    ('wakayama', _('Wakayama'),),
    ('tottori', _('Tottori'),),
    ('shimane', _('Shimane'),),
    ('okayama', _('Okayama'),),
    ('hiroshima', _('Hiroshima'),),
    ('yamaguchi', _('Yamaguchi'),),
    ('tokushima', _('Tokushima'),),
    ('kagawa', _('Kagawa'),),
    ('ehime', _('Ehime'),),
    ('kochi', _('Kochi'),),
    ('fukuoka', _('Fukuoka'),),
    ('saga', _('Saga'),),
    ('nagasaki', _('Nagasaki'),),
    ('kumamoto', _('Kumamoto'),),
    ('oita', _('Oita'),),
    ('miyazaki', _('Miyazaki'),),
    ('kagoshima', _('Kagoshima'),),
    ('okinawa', _('Okinawa'),),
)
