strictness: veryhigh
doc-warnings: yes
test-warnings: yes
max-line-length: 120
uses:
  - django
pylint:
  disable:
    - missing-docstring
    - no-self-use
pep257:
  disable:
    - D100
    - D101
    - D102
    - D103
    - D104
    - D105
    - D203
