inherits:
  - strictness_low

uses:
  - django

pylint:
  options:
    max-line-length: 120
  disable:
    - import-outside-toplevel
    - no-else-return
    - no-else-raise

pep8:
  options:
    max-line-length: 120

mccabe:
  options:
    max-complexity: 9
