#: A list of Peru regions as `choices` in a formfield.
REGION_CHOICES = (
    ('AMA', 'Amazonas'),
    ('ANC', 'Ancash'),
    ('APU', 'Apurímac'),
    ('ARE', 'Arequipa'),
    ('AYA', 'Ayacucho'),
    ('CAJ', 'Cajamarca'),
    ('CAL', 'Callao'),
    ('CUS', 'Cusco'),
    ('HUV', 'Huancavelica'),
    ('HUC', 'Huánuco'),
    ('ICA', 'Ica'),
    ('JUN', 'Junín'),
    ('LAL', 'La Libertad'),
    ('LAM', 'Lambayeque'),
    ('LIM', 'Lima'),
    ('LOR', 'Loreto'),
    ('MDD', 'Madre de Dios'),
    ('MOQ', 'Moquegua'),
    ('PAS', 'Pasco'),
    ('PIU', 'Piura'),
    ('PUN', 'Puno'),
    ('SAM', 'San Martín'),
    ('TAC', 'Tacna'),
    ('TUM', 'Tumbes'),
    ('UCA', 'Ucayali'),
)
