from django.utils.translation import gettext_lazy as _


POSTAL_CODE_REGIONS = (
    ("AB", _("Aberdeen")),
    ("AL", _("St Albans")),
    ("B", _("Birmingham")),
    ("BA", _("Bath")),
    ("BB", _("Blackburn")),
    ("BD", _("Bradford")),
    ("BH", _("Bournemouth")),
    ("BL", _("Bolton")),
    ("BN", _("Brighton")),
    ("BR", _("Bromley")),
    ("BS", _("Bristol")),
    ("BT", _("Belfast")),
    ("CA", _("Carlisle")),
    ("CB", _("Cambridge")),
    ("CF", _("Cardiff")),
    ("CH", _("Chester")),
    ("CM", _("Chelmsford")),
    ("CO", _("Colchester")),
    ("CR", _("Croydon")),
    ("CT", _("Canterbury")),
    ("CV", _("Coventry")),
    ("CW", _("Crewe")),
    ("DA", _("Dartford")),
    ("DD", _("Dundee")),
    ("DE", _("Derby")),
    ("DG", _("Dumfries")),
    ("DH", _("Durham")),
    ("DL", _("Darlington")),
    ("DN", _("Doncaster")),
    ("DT", _("Dorchester")),
    ("DY", _("Dudley")),
    ("E", _("East London")),
    ("EC", _("East Central London")),
    ("EH", _("Edinburgh")),
    ("EN", _("Enfield")),
    ("EX", _("Exeter")),
    ("FK", _("Falkirk")),
    ("FY", _("Blackpool")),
    ("G", _("Glasgow")),
    ("GL", _("Gloucester")),
    ("GU", _("Guildford")),
    ("HA", _("Harrow")),
    ("HD", _("Huddersfield")),
    ("HG", _("Harrogate")),
    ("HP", _("Hemel Hempstead")),
    ("HR", _("Hereford")),
    ("HS", _("Outer Hebrides")),
    ("HU", _("Hull")),
    ("HX", _("Halifax")),
    ("IG", _("Ilford")),
    ("IP", _("Ipswich")),
    ("IV", _("Inverness")),
    ("KA", _("Kilmarnock")),
    ("KT", _("Kingston upon Thames")),
    ("KW", _("Kirkwall")),
    ("KY", _("Kirkcaldy")),
    ("L", _("Liverpool")),
    ("LA", _("Lancaster")),
    ("LD", _("Llandrindod Wells")),
    ("LE", _("Leicester")),
    ("LL", _("Llandudno")),
    ("LN", _("Lincoln")),
    ("LS", _("Leeds")),
    ("LU", _("Luton")),
    ("M", _("Manchester")),
    ("ME", _("Rochester")),
    ("MK", _("Milton Keynes")),
    ("ML", _("Motherwell")),
    ("N", _("North London")),
    ("NE", _("Newcastle upon Tyne")),
    ("NG", _("Nottingham")),
    ("NN", _("Northampton")),
    ("NP", _("Newport")),
    ("NR", _("Norwich")),
    ("NW", _("North West London")),
    ("OL", _("Oldham")),
    ("OX", _("Oxford")),
    ("PA", _("Paisley")),
    ("PE", _("Peterborough")),
    ("PH", _("Perth")),
    ("PL", _("Plymouth")),
    ("PO", _("Portsmouth")),
    ("PR", _("Preston")),
    ("RG", _("Reading")),
    ("RH", _("Redhill")),
    ("RM", _("Romford")),
    ("S", _("Sheffield")),
    ("SA", _("Swansea")),
    ("SE", _("South East London")),
    ("SG", _("Stevenage")),
    ("SK", _("Stockport")),
    ("SL", _("Slough")),
    ("SM", _("Sutton")),
    ("SN", _("Swindon")),
    ("SO", _("Southampton")),
    ("SP", _("Salisbury")),
    ("SR", _("Sunderland")),
    ("SS", _("Southend-on-Sea")),
    ("ST", _("Stoke-on-Trent")),
    ("SW", _("South West London")),
    ("SY", _("Shrewsbury")),
    ("TA", _("Taunton")),
    ("TD", _("Galashiels")),
    ("TF", _("Telford")),
    ("TN", _("Tunbridge Wells")),
    ("TQ", _("Torquay")),
    ("TR", _("Truro")),
    ("TS", _("Cleveland")),
    ("TW", _("Twickenham")),
    ("UB", _("Southall")),
    ("W", _("West London")),
    ("WA", _("Warrington")),
    ("WC", _("Western Central London")),
    ("WD", _("Watford")),
    ("WF", _("Wakefield")),
    ("WN", _("Wigan")),
    ("WR", _("Worcester")),
    ("WS", _("Walsall")),
    ("WV", _("Wolverhampton")),
    ("YO", _("York")),
    ("ZE", _("Lerwick")),

)


POSTAL_CODE_REGIONS_CROWN_DEPENDENCIES = (
    ("GY", _("Guernsey")),
    ("JE", _("Jersey")),
    ("IM", _("Isle of Man")),
)
