"""
SOURCE: https://www.bcb.gov.br/pom/spb/estatistica/port/ASTR003.pdf
Last Update: 12-JUN-2019

Rows where 'Número-Código' is n/a were not included
Sorting: As-is in the Bacen's csv file
"""

BR_BANK_CHOICES = (
    ('001', 'BCO DO BRASIL S.A.'),
    ('070', 'BRB - BCO DE BRASILIA S.A.'),
    ('272', 'AGK CC S.A.'),
    ('136', 'CONF NAC COOP CENTRAIS UNICRED'),
    ('104', 'CAIXA ECONOMICA FEDERAL'),
    ('077', 'BANCO INTER'),
    ('741', 'BCO RIBEIRAO PRETO S.A.'),
    ('739', 'BCO CETELEM S.A.'),
    ('743', 'BANCO SEMEAR'),
    ('100', 'PLANNER CV S.A.'),
    ('096', 'BCO B3 S.A.'),
    ('747', 'BCO RABOBANK INTL BRASIL S.A.'),
    ('322', 'CCR DE ABELARDO LUZ'),
    ('748', 'BCO COOPERATIVO SICREDI S.A.'),
    ('752', 'BCO BNP PARIBAS BRASIL S A'),
    ('091', 'CCCM UNICRED CENTRAL RS'),
    ('399', 'KIRTON BANK'),
    ('108', 'PORTOCRED S.A. - CFI'),
    ('756', 'BANCOOB'),
    ('757', 'BCO KEB HANA DO BRASIL S.A.'),
    ('102', 'XP INVESTIMENTOS CCTVM S/A'),
    ('084', 'UNIPRIME NORTE DO PARANÁ - CC'),
    ('180', 'CM CAPITAL MARKETS CCTVM LTDA'),
    ('066', 'BCO MORGAN STANLEY S.A.'),
    ('015', 'UBS BRASIL CCTVM S.A.'),
    ('143', 'TREVISO CC S.A.'),
    ('062', 'HIPERCARD BM S.A.'),
    ('074', 'BCO. J.SAFRA S.A.'),
    ('099', 'UNIPRIME CENTRAL CCC LTDA.'),
    ('025', 'BCO ALFA S.A.'),
    ('315', 'PI DTVM S.A.'),
    ('075', 'BCO ABN AMRO S.A.'),
    ('040', 'BCO CARGILL S.A.'),
    ('307', 'TERRA INVESTIMENTOS DTVM'),
    ('190', 'SERVICOOP'),
    ('296', 'VISION S.A. CC'),
    ('063', 'BANCO BRADESCARD'),
    ('191', 'NOVA FUTURA CTVM LTDA.'),
    ('064', 'GOLDMAN SACHS DO BRASIL BM S.A'),
    ('097', 'CCC NOROESTE BRASILEIRO LTDA.'),
    ('016', 'CCM DESP TRÂNS SC E RS'),
    ('299', 'SOROCRED CFI S.A.'),
    ('012', 'BANCO INBURSA'),
    ('003', 'BCO DA AMAZONIA S.A.'),
    ('060', 'CONFIDENCE CC S.A.'),
    ('037', 'BCO DO EST. DO PA S.A.'),
    ('159', 'CASA CREDITO S.A. SCM'),
    ('172', 'ALBATROSS CCV S.A'),
    ('085', 'COOP CENTRAL AILOS'),
    ('114', 'CENTRAL COOPERATIVA DE CRÉDITO NO ESTADO DO ESPÍRITO SANTO'),
    ('036', 'BCO BBI S.A.'),
    ('394', 'BCO BRADESCO FINANC. S.A.'),
    ('004', 'BCO DO NORDESTE DO BRASIL S.A.'),
    ('320', 'BCO CCB BRASIL S.A.'),
    ('189', 'HS FINANCEIRA'),
    ('105', 'LECCA CFI S.A.'),
    ('076', 'BCO KDB BRASIL S.A.'),
    ('082', 'BANCO TOPÁZIO S.A.'),
    ('286', 'CCR DE OURO'),
    ('093', 'PÓLOCRED SCMEPP LTDA.'),
    ('273', 'CCR DE SÃO MIGUEL DO OESTE'),
    ('290', 'PAGSEGURO'),
    ('157', 'ICAP DO BRASIL CTVM LTDA.'),
    ('183', 'SOCRED SA - SCMEPP'),
    ('014', 'STATE STREET BR S.A. BCO COMERCIAL'),
    ('130', 'CARUANA SCFI'),
    ('127', 'CODEPE CVC S.A.'),
    ('079', 'BCO ORIGINAL DO AGRO S/A'),
    ('081', 'BANCOSEGURO S.A.'),
    ('133', 'CRESOL CONFEDERAÇÃO'),
    ('121', 'BCO AGIBANK S.A.'),
    ('083', 'BCO DA CHINA BRASIL S.A.'),
    ('138', 'GET MONEY CC LTDA'),
    ('024', 'BCO BANDEPE S.A.'),
    ('319', 'OM DTVM LTDA'),
    ('095', 'TRAVELEX BANCO DE CÂMBIO S.A.'),
    ('094', 'BANCO FINAXIS'),
    ('118', 'STANDARD CHARTERED BI S.A.'),
    ('276', 'SENFF S.A. - CFI'),
    ('092', 'BRK S.A. CFI'),
    ('047', 'BCO DO EST. DE SE S.A.'),
    ('144', 'BEXS BCO DE CAMBIO S.A.'),
    ('126', 'BR PARTNERS BI'),
    ('325', 'ÓRAMA DTVM S.A.'),
    ('301', 'BPP IP S.A.'),
    ('173', 'BRL TRUST DTVM SA'),
    ('119', 'BCO WESTERN UNION'),
    ('309', 'CAMBIONET CC LTDA'),
    ('254', 'PARANA BCO S.A.'),
    ('268', 'BARIGUI CH'),
    ('107', 'BCO BOCOM BBM S.A.'),
    ('412', 'BCO CAPITAL S.A.'),
    ('124', 'BCO WOORI BANK DO BRASIL S.A.'),
    ('149', 'FACTA S.A. CFI'),
    ('197', 'STONE PAGAMENTOS S.A.'),
    ('142', 'BROKER BRASIL CC LTDA.'),
    ('389', 'BCO MERCANTIL DO BRASIL S.A.'),
    ('184', 'BCO ITAÚ BBA S.A.'),
    ('634', 'BCO TRIANGULO S.A.'),
    ('545', 'SENSO CCVM S.A.'),
    ('132', 'ICBC DO BRASIL BM S.A.'),
    ('298', 'VIPS CC LTDA.'),
    ('321', 'CREFAZ SCMEPP LTDA'),
    ('260', 'NU PAGAMENTOS S.A.'),
    ('129', 'UBS BRASIL BI S.A.'),
    ('128', 'MS BANK S.A. BCO DE CÂMBIO'),
    ('194', 'PARMETAL DTVM LTDA'),
    ('310', 'VORTX DTVM LTDA.'),
    ('163', 'COMMERZBANK BRASIL S.A. - BCO MÚLTIPLO'),
    ('280', 'AVISTA S.A. CFI'),
    ('146', 'GUITTA CC LTDA'),
    ('279', 'CCR DE PRIMAVERA DO LESTE'),
    ('182', 'DACASA FINANCEIRA S/A - SCFI'),
    ('278', 'GENIAL INVESTIMENTOS CVM S.A.'),
    ('271', 'IB CCTVM LTDA'),
    ('021', 'BCO BANESTES S.A.'),
    ('246', 'BCO ABC BRASIL S.A.'),
    ('292', 'BS2 DTVM S.A.'),
    ('751', 'SCOTIABANK BRASIL'),
    ('208', 'BANCO BTG PACTUAL S.A.'),
    ('746', 'BCO MODAL S.A.'),
    ('241', 'BCO CLASSICO S.A.'),
    ('336', 'BCO C6 S.A.'),
    ('612', 'BCO GUANABARA S.A.'),
    ('604', 'BCO INDUSTRIAL DO BRASIL S.A.'),
    ('505', 'BCO CREDIT SUISSE (BRL) S.A.'),
    ('329', 'SCD QI                             '),
    ('196', 'FAIR CC S.A.'),
    ('300', 'BCO LA NACION ARGENTINA'),
    ('477', 'CITIBANK N.A.'),
    ('266', 'BCO CEDULA S.A.'),
    ('122', 'BCO BRADESCO BERJ S.A.'),
    ('376', 'BCO J.P. MORGAN S.A.'),
    ('473', 'BCO CAIXA GERAL BRASIL S.A.'),
    ('745', 'BCO CITIBANK S.A.'),
    ('120', 'BCO RODOBENS S.A.'),
    ('265', 'BCO FATOR S.A.'),
    ('007', 'BNDES'),
    ('188', 'ATIVA S.A. INVESTIMENTOS CCTVM'),
    ('134', 'BGC LIQUIDEZ DTVM LTDA'),
    ('641', 'BCO ALVORADA S.A.'),
    ('029', 'BANCO ITAÚ CONSIGNADO S.A.'),
    ('243', 'BCO MÁXIMA S.A.'),
    ('078', 'HAITONG BI DO BRASIL S.A.'),
    ('111', 'OLIVEIRA TRUST DTVM S.A.'),
    ('306', 'PORTOPAR DTVM LTDA'),
    ('017', 'BNY MELLON BCO S.A.'),
    ('174', 'PERNAMBUCANAS FINANC S.A. CFI'),
    ('495', 'BCO LA PROVINCIA B AIRES BCE'),
    ('125', 'BRASIL PLURAL S.A. BCO.'),
    ('488', 'JPMORGAN CHASE BANK'),
    ('065', 'BCO ANDBANK S.A.'),
    ('492', 'ING BANK N.V.'),
    ('145', 'LEVYCAM CCV LTDA'),
    ('250', 'BCV'),
    ('494', 'BCO REP ORIENTAL URUGUAY BCE'),
    ('253', 'BEXS CC S.A.'),
    ('269', 'HSBC BANCO DE INVESTIMENTO'),
    ('213', 'BCO ARBI S.A.'),
    ('139', 'INTESA SANPAOLO BRASIL S.A. BM'),
    ('018', 'BCO TRICURY S.A.'),
    ('422', 'BCO SAFRA S.A.'),
    ('630', 'SMARTBANK'),
    ('224', 'BCO FIBRA S.A.'),
    ('600', 'BCO LUSO BRASILEIRO S.A.'),
    ('623', 'BANCO PAN'),
    ('204', 'BCO BRADESCO CARTOES S.A.'),
    ('655', 'BCO VOTORANTIM S.A.'),
    ('479', 'BCO ITAUBANK S.A.'),
    ('456', 'BCO MUFG BRASIL S.A.'),
    ('464', 'BCO SUMITOMO MITSUI BRASIL S.A.'),
    ('341', 'ITAÚ UNIBANCO S.A.'),
    ('237', 'BCO BRADESCO S.A.'),
    ('613', 'OMNI BANCO S.A.'),
    ('652', 'ITAÚ UNIBANCO HOLDING S.A.'),
    ('637', 'BCO SOFISA S.A.'),
    ('653', 'BCO INDUSVAL S.A.'),
    ('069', 'BCO CREFISA S.A.'),
    ('370', 'BCO MIZUHO S.A.'),
    ('249', 'BANCO INVESTCRED UNIBANCO S.A.'),
    ('318', 'BCO BMG S.A.'),
    ('626', 'BCO FICSA S.A.'),
    ('270', 'SAGITUR CC LTDA'),
    ('366', 'BCO SOCIETE GENERALE BRASIL'),
    ('113', 'MAGLIANO S.A. CCVM'),
    ('131', 'TULLETT PREBON BRASIL CVC LTDA'),
    ('011', 'C.SUISSE HEDGING-GRIFFO CV S/A'),
    ('611', 'BCO PAULISTA S.A.'),
    ('755', 'BOFA MERRILL LYNCH BM S.A.'),
    ('089', 'CCR REG MOGIANA'),
    ('643', 'BCO PINE S.A.'),
    ('140', 'EASYNVEST - TÍTULO CV SA'),
    ('707', 'BCO DAYCOVAL S.A'),
    ('288', 'CAROL DTVM LTDA.'),
    ('101', 'RENASCENCA DTVM LTDA'),
    ('487', 'DEUTSCHE BANK S.A.BCO ALEMAO'),
    ('233', 'BANCO CIFRA'),
    ('177', 'GUIDE'),
    ('633', 'BCO RENDIMENTO S.A.'),
    ('218', 'BCO BS2 S.A.'),
    ('169', 'BCO OLÉ BONSUCESSO CONSIGNADO S.A.'),
    ('293', 'LASTRO RDV DTVM LTDA'),
    ('285', 'FRENTE CC LTDA.'),
    ('080', 'B&T CC LTDA.'),
    ('753', 'NOVO BCO CONTINENTAL S.A. - BM'),
    ('222', 'BCO CRÉDIT AGRICOLE BR S.A.'),
    ('281', 'CCR COOPAVEL'),
    ('754', 'BANCO SISTEMA'),
    ('098', 'CREDIALIANÇA CCR'),
    ('610', 'BCO VR S.A.'),
    ('712', 'BCO OURINVEST S.A.'),
    ('010', 'CREDICOAMO'),
    ('283', 'RB CAPITAL INVESTIMENTOS DTVM LTDA.'),
    ('033', 'BCO SANTANDER (BRASIL) S.A.'),
    ('217', 'BANCO JOHN DEERE S.A.'),
    ('041', 'BCO DO ESTADO DO RS S.A.'),
    ('117', 'ADVANCED CC LTDA'),
    ('654', 'BCO A.J. RENNER S.A.'),
    ('212', 'BANCO ORIGINAL'),
    ('289', 'DECYSEO CC LTDA.'),
)
