"""
Kenya Counties Data
"""

from django.utils.translation import gettext_lazy as _

COUNTY_CHOICES = (
    ("MOMBASA", _("MOMBASA")),
    ("KWALE", _("KWALE")),
    ("KILIFI", _("KILIFI")),
    ("TANA RIVER", _("TANA RIVER")),
    ("LAMU", _("LAMU")),
    ("TAITA-TAVETA", _("TAITA-TAVETA")),
    ("GARISSA", _("GARISSA")),
    ("WAJIR", _("WAJIR")),
    ("MANDERA", _("MANDERA")),
    ("MARSABIT", _("MARSABIT")),
    ("ISIOLO", _("ISIOLO")),
    ("MERU", _("MERU")),
    ("THARAKA-NITHI", _("THARAKA-NITHI")),
    ("EMBU", _("EMBU")),
    ("KITUI", _("KITUI")),
    ("MACHAKOS", _("MACHAKOS")),
    ("MAKUENI", _("MAKUENI")),
    ("NYANDARUA", _("NYANDARUA")),
    ("NYERI", _("NYERI")),
    ("KIRINYAGA", _("KIRINYAGA")),
    ("MURANGA", _("MURANGA")),
    ("KIAMBU", _("KIAMBU")),
    ("TURKANA", _("TURKANA")),
    ("WEST POKOT", _("WEST POKOT")),
    ("SAMBURU", _("SAMBURU")),
    ("TRANS-NZOIA", _("TRANS-NZOIA")),
    ("UASIN GISHU", _("UASIN GISHU")),
    ("ELGEYO-MARAKWET", _("ELGEYO-MARAKWET")),
    ("NANDI", _("NANDI")),
    ("BARINGO", _("BARINGO")),
    ("LAIKIPIA", _("LAIKIPIA")),
    ("NAKURU", _("NAKURU")),
    ("NAROK", _("NAROK")),
    ("KAJIADO", _("KAJIADO")),
    ("KERICHO", _("KERICHO")),
    ("BOMET", _("BOMET")),
    ("KAKAMEGA", _("KAKAMEGA")),
    ("VIHIGA", _("VIHIGA")),
    ("BUNGOMA", _("BUNGOMA")),
    ("BUSIA", _("BUSIA")),
    ("SIAYA", _("SIAYA")),
    ("KISUMU", _("KISUMU")),
    ("HOMA BAY", _("HOMA BAY")),
    ("MIGORI", _("MIGORI")),
    ("KISII", _("KISII")),
    ("NYAMIRA", _("NYAMIRA")),
    ("NAIROBI", _("NAIROBI")),
)
