#: A list of Ecuador provinces as `choices` in a formfield.
PROVINCE_CHOICES = (
    ('A', 'Azuay'),
    ('B', 'Bolívar'),
    ('F', 'Cañar'),
    ('C', 'Carchi'),
    ('H', 'Chimborazo'),
    ('X', 'Cotopaxi'),
    ('O', 'El Oro'),
    ('E', 'Esmeraldas'),
    ('W', 'Galápagos'),
    ('G', 'Guayas'),
    ('I', 'Imbabura'),
    ('L', 'Loja'),
    ('R', 'Los Ríos'),
    ('M', 'Manabí'),
    ('S', 'Morona Santiago'),
    ('N', 'Napo'),
    ('D', 'Orellana'),
    ('Y', 'Pastaza'),
    ('P', 'Pichincha'),
    ('SE', 'Santa Elena'),
    ('SD', 'Santo Domingo de los Tsáchilas'),
    ('U', 'Sucumbíos'),
    ('T', 'Tungurahua'),
    ('Z', 'Zamora Chinchipe'),
)
