# coding: utf-8
from __future__ import unicode_literals

REGION_HOVEDSTADEN = (
    ('albertslund', 'Albertslund'),
    ('alleroed', 'Allerød'),
    ('ballerup', 'Ballerup'),
    ('bornholm', 'Bornholm'),
    ('broendby', 'Brøndby'),
    ('dragoer', 'Dragør'),
    ('egedal', 'Egedal'),
    ('fredensborg', 'Fredensborg'),
    ('frederiksberg', 'Frederiksberg'),
    ('frederikssund', 'Frederikssund'),
    ('furesoe', 'Furesø'),
    ('gentofte', 'Gentofte'),
    ('gladsaxe', 'Gladsaxe'),
    ('glostrup', 'Glostrup'),
    ('gribskov', 'Gribskov'),
    ('halsnaes', 'Halsnæs'),
    ('helsingoer', 'Helsingør'),
    ('herlev', 'Herlev'),
    ('hilleroed', 'Hillerød'),
    ('hvidovre', 'Hvidovre'),
    ('hoeje-taastrup', 'Høje-Taastrup'),
    ('hoersholm', 'Hørsholm'),
    ('ishoej', 'Ishøj'),
    ('koebenhavn', 'København'),
    ('lyngby-taarbaek', 'Lyngby-Taarbæk'),
    ('rudersdal', 'Rudersdal'),
    ('roedovre', 'Rødovre'),
    ('taarnby', 'Tårnby'),
    ('vallensbaek', 'Vallensbæk'),
)

REGION_MIDTJYLLAND = (
    ('favrskov', 'Favrskov'),
    ('hedensted', 'Hedensted'),
    ('herning', 'Herning'),
    ('holstebro', 'Holstebro'),
    ('horsens', 'Horsens'),
    ('ikast-Brande', 'Ikast-Brande'),
    ('lemvig', 'Lemvig'),
    ('norddjurs', 'Norddjurs'),
    ('odder', 'Odder'),
    ('randers', 'Randers'),
    ('ringkoebing-skjern', 'Ringkøbing-Skjern'),
    ('samsoe', 'Samsø'),
    ('silkeborg', 'Silkeborg'),
    ('skanderborg', 'Skanderborg'),
    ('skive', 'Skive'),
    ('struer', 'Struer'),
    ('syddjurs', 'Syddjurs'),
    ('viborg', 'Viborg'),
    ('aarhus', 'Aarhus'),
)

REGION_NORDJYLLAND = (
    ('broenderslev', 'Brønderslev'),
    ('frederikshavn', 'Frederikshavn'),
    ('hjoerring', 'Hjørring'),
    ('jammerbugt', 'Jammerbugt'),
    ('laesoe', 'Læsø'),
    ('mariagerfjord', 'Mariagerfjord'),
    ('morsoe', 'Morsø'),
    ('rebild', 'Rebild'),
    ('thisted', 'Thisted'),
    ('vesthimmerland', 'Vesthimmerland'),
    ('aalborg', 'Aalborg'),
)

REGION_SJAELLAND = (
    ('faxe', 'Faxe'),
    ('greve', 'Greve'),
    ('guldborgsund', 'Guldborgsund'),
    ('holbaek', 'Holbæk'),
    ('kalundborg', 'Kalundborg'),
    ('koege', 'Køge'),
    ('lejre', 'Lejre'),
    ('lolland', 'Lolland'),
    ('naestved', 'Næstved'),
    ('odsherred', 'Odsherred'),
    ('ringsted', 'Ringsted'),
    ('roskilde', 'Roskilde'),
    ('slagelse', 'Slagelse'),
    ('solroed', 'Solrød'),
    ('soroe', 'Sorø'),
    ('stevns', 'Stevns'),
    ('vordingborg', 'Vordingborg'),
)

REGION_SYDDANMARK = (
    ('assens', 'Assens'),
    ('billund', 'Billund'),
    ('esbjerg', 'Esbjerg'),
    ('fanoe', 'Fanø'),
    ('fredericia', 'Fredericia'),
    ('faaborg-Midtfyn', 'Faaborg-Midtfyn'),
    ('haderslev', 'Haderslev'),
    ('kerteminde', 'Kerteminde'),
    ('kolding', 'Kolding'),
    ('langeland', 'Langeland'),
    ('middelfart', 'Middelfart'),
    ('nordfyn', 'Nordfyn'),
    ('nyborg', 'Nyborg'),
    ('odense', 'Odense'),
    ('svendborg', 'Svendborg'),
    ('soenderborg', 'Sønderborg'),
    ('toender', 'Tønder'),
    ('varde', 'Varde'),
    ('vejen', 'Vejen'),
    ('vejle', 'Vejle'),
    ('aeroe', 'Ærø'),
    ('aabenraa', 'Aabenraa'),
)

DK_MUNICIPALITIES = (
    ('Region Hovedstaden', REGION_HOVEDSTADEN),
    ('Region Midtjylland', REGION_MIDTJYLLAND),
    ('Region Nordjylland', REGION_NORDJYLLAND),
    ('Region Sjælland', REGION_SJAELLAND),
    ('Region Syddanmark', REGION_SYDDANMARK),
)
