from __future__ import unicode_literals

REGION_HOVEDSTADEN = [
    ('albertslund', 'Albertslund'),
    ('allerød', 'Allerød'),
    ('ballerup', 'Ballerup'),
    ('bornholm', 'Bornholm'),
    ('brøndby', 'Brøndby'),
    ('dragør', 'Dragør'),
    ('egedal', 'Egedal'),
    ('fredensborg', 'Fredensborg'),
    ('frederiksberg', 'Frederiksberg'),
    ('frederikssund', 'Frederikssund'),
    ('furesø', 'Furesø'),
    ('gentofte', 'Gentofte'),
    ('gladsaxe', 'Gladsaxe'),
    ('glostrup', 'Glostrup'),
    ('gribskov', 'Gribskov'),
    ('halsnæs', 'Halsnæs'),
    ('helsingør', 'Helsingør'),
    ('herlev', 'Herlev'),
    ('hillerød', 'Hillerød'),
    ('hvidovre', 'Hvidovre'),
    ('høje-Taastrup', 'Høje-Taastrup'),
    ('hørsholm', 'Hørsholm'),
    ('ishøj', 'Ishøj'),
    ('københavn', 'København'),
    ('lyngby-Taarbæk', 'Lyngby-Taarbæk'),
    ('rudersdal', 'Rudersdal'),
    ('rødovre', 'Rødovre'),
    ('tårnby', 'Tårnby'),
    ('vallensbæk', 'Vallensbæk'),
]

REGION_MIDTJYLLAND = [
    ('favrskov', 'Favrskov'),
    ('hedensted', 'Hedensted'),
    ('herning', 'Herning'),
    ('holstebro', 'Holstebro'),
    ('horsens', 'Horsens'),
    ('ikast-Brande', 'Ikast-Brande'),
    ('lemvig', 'Lemvig'),
    ('norddjurs', 'Norddjurs'),
    ('odder', 'Odder'),
    ('randers', 'Randers'),
    ('ringkøbing-Skjern', 'Ringkøbing-Skjern'),
    ('samsø', 'Samsø'),
    ('silkeborg', 'Silkeborg'),
    ('skanderborg', 'Skanderborg'),
    ('skive', 'Skive'),
    ('struer', 'Struer'),
    ('syddjurs', 'Syddjurs'),
    ('viborg', 'Viborg'),
    ('aarhus', 'Aarhus'),
]

REGION_NORDJYLLAND = [
    ('brønderslev', 'Brønderslev'),
    ('frederikshavn', 'Frederikshavn'),
    ('hjørring', 'Hjørring'),
    ('jammerbugt', 'Jammerbugt'),
    ('læsø', 'Læsø'),
    ('mariagerfjord', 'Mariagerfjord'),
    ('morsø', 'Morsø'),
    ('rebild', 'Rebild'),
    ('thisted', 'Thisted'),
    ('vesthimmerland', 'Vesthimmerland'),
    ('aalborg', 'Aalborg'),
]

REGION_SJAELLAND = [
    ('faxe', 'Faxe'),
    ('greve', 'Greve'),
    ('guldborgsund', 'Guldborgsund'),
    ('holbæk', 'Holbæk'),
    ('kalundborg', 'Kalundborg'),
    ('køge', 'Køge'),
    ('lejre', 'Lejre'),
    ('lolland', 'Lolland'),
    ('næstved', 'Næstved'),
    ('odsherred', 'Odsherred'),
    ('ringsted', 'Ringsted'),
    ('roskilde', 'Roskilde'),
    ('slagelse', 'Slagelse'),
    ('solrød', 'Solrød'),
    ('sorø', 'Sorø'),
    ('stevns', 'Stevns'),
    ('vordingborg', 'Vordingborg'),
]

REGION_SYDDANMARK = [
    ('assens', 'Assens'),
    ('billund', 'Billund'),
    ('esbjerg', 'Esbjerg'),
    ('fanø', 'Fanø'),
    ('fredericia', 'Fredericia'),
    ('faaborg-Midtfyn', 'Faaborg-Midtfyn'),
    ('haderslev', 'Haderslev'),
    ('kerteminde', 'Kerteminde'),
    ('kolding', 'Kolding'),
    ('langeland', 'Langeland'),
    ('middelfart', 'Middelfart'),
    ('nordfyn', 'Nordfyn'),
    ('nyborg', 'Nyborg'),
    ('odense', 'Odense'),
    ('svendborg', 'Svendborg'),
    ('sønderborg', 'Sønderborg'),
    ('tønder', 'Tønder'),
    ('varde', 'Varde'),
    ('vejen', 'Vejen'),
    ('vejle', 'Vejle'),
    ('ærø', 'Ærø'),
    ('aabenraa', 'Aabenraa'),
]

DK_MUNICIPALITIES = [
    REGION_HOVEDSTADEN,
    REGION_MIDTJYLLAND,
    REGION_NORDJYLLAND,
    REGION_SJAELLAND,
    REGION_SYDDANMARK,
]
