# -*- coding: utf-8 -*-
from __future__ import unicode_literals

#: A list of Chilean communes as `choices` in a formfield.
# taken from http://es.wikipedia.org/wiki/Anexo:Comunas_de_Chile
COMMUNE_CHOICES = (
    ('Arica', 'Arica'),
    ('Camarones', 'Camarones'),
    ('Putre', 'Putre'),
    ('General Lagos', 'General Lagos'),
    ('Iquique', 'Iquique'),
    ('Alto Hospicio', 'Alto Hospicio'),
    ('Pozo Almonte', 'Pozo Almonte'),
    ('Camiña', 'Camiña'),
    ('Colchane', 'Colchane'),
    ('Huara', 'Huara'),
    ('Pica', 'Pica'),
    ('Antofagasta', 'Antofagasta'),
    ('Mejillones', 'Mejillones'),
    ('Sierra Gorda', 'Sierra Gorda'),
    ('Taltal', 'Taltal'),
    ('Calama', 'Calama'),
    ('Ollagüe', 'Ollagüe'),
    ('San Pedro de Atacama', 'San Pedro de Atacama'),
    ('Tocopilla', 'Tocopilla'),
    ('María Elena', 'María Elena'),
    ('Copiapó', 'Copiapó'),
    ('Caldera', 'Caldera'),
    ('Tierra Amarilla', 'Tierra Amarilla'),
    ('Chañaral', 'Chañaral'),
    ('Diego de Almagro', 'Diego de Almagro'),
    ('Vallenar', 'Vallenar'),
    ('Alto del Carmen', 'Alto del Carmen'),
    ('Freirina', 'Freirina'),
    ('Huasco', 'Huasco'),
    ('La Serena', 'La Serena'),
    ('Coquimbo', 'Coquimbo'),
    ('Andacollo', 'Andacollo'),
    ('La Higuera', 'La Higuera'),
    ('Paiguano', 'Paiguano'),
    ('Vicuña', 'Vicuña'),
    ('Illapel', 'Illapel'),
    ('Canela', 'Canela'),
    ('Los Vilos', 'Los Vilos'),
    ('Salamanca', 'Salamanca'),
    ('Ovalle', 'Ovalle'),
    ('Combarbalá', 'Combarbalá'),
    ('Monte Patria', 'Monte Patria'),
    ('Punitaqui', 'Punitaqui'),
    ('Río Hurtado', 'Río Hurtado'),
    ('Valparaíso', 'Valparaíso'),
    ('Casablanca', 'Casablanca'),
    ('Concón', 'Concón'),
    ('Juan Fernández', 'Juan Fernández'),
    ('Puchuncaví', 'Puchuncaví'),
    ('Quintero', 'Quintero'),
    ('Viña del Mar', 'Viña del Mar'),
    ('Isla de Pascua', 'Isla de Pascua'),
    ('Los Andes', 'Los Andes'),
    ('Calle Larga', 'Calle Larga'),
    ('Rinconada', 'Rinconada'),
    ('San Esteban', 'San Esteban'),
    ('La Ligua', 'La Ligua'),
    ('Cabildo', 'Cabildo'),
    ('Papudo', 'Papudo'),
    ('Petorca', 'Petorca'),
    ('Zapallar', 'Zapallar'),
    ('Quillota', 'Quillota'),
    ('Calera', 'Calera'),
    ('Hijuelas', 'Hijuelas'),
    ('La Cruz', 'La Cruz'),
    ('Nogales', 'Nogales'),
    ('San Antonio', 'San Antonio'),
    ('Algarrobo', 'Algarrobo'),
    ('Cartagena', 'Cartagena'),
    ('El Quisco', 'El Quisco'),
    ('El Tabo', 'El Tabo'),
    ('Santo Domingo', 'Santo Domingo'),
    ('San Felipe', 'San Felipe'),
    ('Catemu', 'Catemu'),
    ('Llaillay', 'Llaillay'),
    ('Panquehue', 'Panquehue'),
    ('Putaendo', 'Putaendo'),
    ('Santa María', 'Santa María'),
    ('Quilpué', 'Quilpué'),
    ('Limache', 'Limache'),
    ('Olmué', 'Olmué'),
    ('Villa Alemana', 'Villa Alemana'),
    ('Rancagua', 'Rancagua'),
    ('Codegua', 'Codegua'),
    ('Coinco', 'Coinco'),
    ('Coltauco', 'Coltauco'),
    ('Doñihue', 'Doñihue'),
    ('Graneros', 'Graneros'),
    ('Las Cabras', 'Las Cabras'),
    ('Machalí', 'Machalí'),
    ('Malloa', 'Malloa'),
    ('Mostazal', 'Mostazal'),
    ('Olivar', 'Olivar'),
    ('Peumo', 'Peumo'),
    ('Pichidegua', 'Pichidegua'),
    ('Quinta de Tilcoco', 'Quinta de Tilcoco'),
    ('Rengo', 'Rengo'),
    ('Requínoa', 'Requínoa'),
    ('San Vicente', 'San Vicente'),
    ('Pichilemu', 'Pichilemu'),
    ('La Estrella', 'La Estrella'),
    ('Litueche', 'Litueche'),
    ('Marchihue', 'Marchihue'),
    ('Navidad', 'Navidad'),
    ('Paredones', 'Paredones'),
    ('San Fernando', 'San Fernando'),
    ('Chépica', 'Chépica'),
    ('Chimbarongo', 'Chimbarongo'),
    ('Lolol', 'Lolol'),
    ('Nancagua', 'Nancagua'),
    ('Palmilla', 'Palmilla'),
    ('Peralillo', 'Peralillo'),
    ('Placilla', 'Placilla'),
    ('Pumanque', 'Pumanque'),
    ('Santa Cruz', 'Santa Cruz'),
    ('Talca', 'Talca'),
    ('Constitución', 'Constitución'),
    ('Curepto', 'Curepto'),
    ('Empedrado', 'Empedrado'),
    ('Maule', 'Maule'),
    ('Pelarco', 'Pelarco'),
    ('Pencahue', 'Pencahue'),
    ('Río Claro', 'Río Claro'),
    ('San Clemente', 'San Clemente'),
    ('San Rafael', 'San Rafael'),
    ('Cauquenes', 'Cauquenes'),
    ('Chanco', 'Chanco'),
    ('Pelluhue', 'Pelluhue'),
    ('Curicó', 'Curicó'),
    ('Hualañé', 'Hualañé'),
    ('Licantén', 'Licantén'),
    ('Molina', 'Molina'),
    ('Rauco', 'Rauco'),
    ('Romeral', 'Romeral'),
    ('Sagrada Familia', 'Sagrada Familia'),
    ('Teno', 'Teno'),
    ('Vichuquén', 'Vichuquén'),
    ('Linares', 'Linares'),
    ('Colbún', 'Colbún'),
    ('Longaví', 'Longaví'),
    ('Parral', 'Parral'),
    ('Retiro', 'Retiro'),
    ('San Javier', 'San Javier'),
    ('Villa Alegre', 'Villa Alegre'),
    ('Yerbas Buenas', 'Yerbas Buenas'),
    ('Concepción', 'Concepción'),
    ('Coronel', 'Coronel'),
    ('Chiguayante', 'Chiguayante'),
    ('Florida', 'Florida'),
    ('Hualqui', 'Hualqui'),
    ('Lota', 'Lota'),
    ('Penco', 'Penco'),
    ('San Pedro de La Paz', 'San Pedro de La Paz'),
    ('Santa Juana', 'Santa Juana'),
    ('Talcahuano', 'Talcahuano'),
    ('Tomé', 'Tomé'),
    ('Hualpén', 'Hualpén'),
    ('Lebu', 'Lebu'),
    ('Arauco', 'Arauco'),
    ('Cañete', 'Cañete'),
    ('Contulmo', 'Contulmo'),
    ('Curanilahue', 'Curanilahue'),
    ('Los Álamos', 'Los Álamos'),
    ('Tirúa', 'Tirúa'),
    ('Los Ángeles', 'Los Ángeles'),
    ('Antuco', 'Antuco'),
    ('Cabrero', 'Cabrero'),
    ('Laja', 'Laja'),
    ('Mulchén', 'Mulchén'),
    ('Nacimiento', 'Nacimiento'),
    ('Negrete', 'Negrete'),
    ('Quilaco', 'Quilaco'),
    ('Quilleco', 'Quilleco'),
    ('San Rosendo', 'San Rosendo'),
    ('Santa Bárbara', 'Santa Bárbara'),
    ('Tucapel', 'Tucapel'),
    ('Yumbel', 'Yumbel'),
    ('Alto Biobío', 'Alto Biobío'),
    ('Chillán', 'Chillán'),
    ('Bulnes', 'Bulnes'),
    ('Cobquecura', 'Cobquecura'),
    ('Coelemu', 'Coelemu'),
    ('Coihueco', 'Coihueco'),
    ('Chillán Viejo', 'Chillán Viejo'),
    ('El Carmen', 'El Carmen'),
    ('Ninhue', 'Ninhue'),
    ('Ñiquén', 'Ñiquén'),
    ('Pemuco', 'Pemuco'),
    ('Pinto', 'Pinto'),
    ('Portezuelo', 'Portezuelo'),
    ('Quillón', 'Quillón'),
    ('Quirihue', 'Quirihue'),
    ('Ránquil', 'Ránquil'),
    ('San Carlos', 'San Carlos'),
    ('San Fabián', 'San Fabián'),
    ('San Ignacio', 'San Ignacio'),
    ('San Nicolás', 'San Nicolás'),
    ('Treguaco', 'Treguaco'),
    ('Yungay', 'Yungay'),
    ('Temuco', 'Temuco'),
    ('Carahue', 'Carahue'),
    ('Cunco', 'Cunco'),
    ('Curarrehue', 'Curarrehue'),
    ('Freire', 'Freire'),
    ('Galvarino', 'Galvarino'),
    ('Gorbea', 'Gorbea'),
    ('Lautaro', 'Lautaro'),
    ('Loncoche', 'Loncoche'),
    ('Melipeuco', 'Melipeuco'),
    ('Nueva Imperial', 'Nueva Imperial'),
    ('Padre Las Casas', 'Padre Las Casas'),
    ('Perquenco', 'Perquenco'),
    ('Pitrufquén', 'Pitrufquén'),
    ('Pucón', 'Pucón'),
    ('Saavedra', 'Saavedra'),
    ('Teodoro Schmidt', 'Teodoro Schmidt'),
    ('Toltén', 'Toltén'),
    ('Vilcún', 'Vilcún'),
    ('Villarrica', 'Villarrica'),
    ('Cholchol', 'Cholchol'),
    ('Angol', 'Angol'),
    ('Collipulli', 'Collipulli'),
    ('Curacautín', 'Curacautín'),
    ('Ercilla', 'Ercilla'),
    ('Lonquimay', 'Lonquimay'),
    ('Los Sauces', 'Los Sauces'),
    ('Lumaco', 'Lumaco'),
    ('Purén', 'Purén'),
    ('Renaico', 'Renaico'),
    ('Traiguén', 'Traiguén'),
    ('Victoria', 'Victoria'),
    ('Valdivia', 'Valdivia'),
    ('Corral', 'Corral'),
    ('Lanco', 'Lanco'),
    ('Los Lagos', 'Los Lagos'),
    ('Máfil', 'Máfil'),
    ('Mariquina', 'Mariquina'),
    ('Paillaco', 'Paillaco'),
    ('Panguipulli', 'Panguipulli'),
    ('La Unión', 'La Unión'),
    ('Futrono', 'Futrono'),
    ('Lago Ranco', 'Lago Ranco'),
    ('Río Bueno', 'Río Bueno'),
    ('Puerto Montt', 'Puerto Montt'),
    ('Calbuco', 'Calbuco'),
    ('Cochamó', 'Cochamó'),
    ('Fresia', 'Fresia'),
    ('Frutillar', 'Frutillar'),
    ('Los Muermos', 'Los Muermos'),
    ('Llanquihue', 'Llanquihue'),
    ('Maullín', 'Maullín'),
    ('Puerto Varas', 'Puerto Varas'),
    ('Castro', 'Castro'),
    ('Ancud', 'Ancud'),
    ('Chonchi', 'Chonchi'),
    ('Curaco de Vélez', 'Curaco de Vélez'),
    ('Dalcahue', 'Dalcahue'),
    ('Puqueldón', 'Puqueldón'),
    ('Queilén', 'Queilén'),
    ('Quellón', 'Quellón'),
    ('Quemchi', 'Quemchi'),
    ('Quinchao', 'Quinchao'),
    ('Osorno', 'Osorno'),
    ('Puerto Octay', 'Puerto Octay'),
    ('Purranque', 'Purranque'),
    ('Puyehue', 'Puyehue'),
    ('Río Negro', 'Río Negro'),
    ('San Juan de la Costa', 'San Juan de la Costa'),
    ('San Pablo', 'San Pablo'),
    ('Chaitén', 'Chaitén'),
    ('Futaleufú', 'Futaleufú'),
    ('Hualaihué', 'Hualaihué'),
    ('Palena', 'Palena'),
    ('Coyhaique', 'Coyhaique'),
    ('Lago Verde', 'Lago Verde'),
    ('Aysén', 'Aysén'),
    ('Cisnes', 'Cisnes'),
    ('Guaitecas', 'Guaitecas'),
    ('Cochrane', 'Cochrane'),
    ('O\'Higgins', 'O\'Higgins'),
    ('Tortel', 'Tortel'),
    ('Chile Chico', 'Chile Chico'),
    ('Río Ibáñez', 'Río Ibáñez'),
    ('Punta Arenas', 'Punta Arenas'),
    ('Laguna Blanca', 'Laguna Blanca'),
    ('Río Verde', 'Río Verde'),
    ('San Gregorio', 'San Gregorio'),
    ('Cabo de Hornos', 'Cabo de Hornos'),
    ('Antártica', 'Antártica'),
    ('Porvenir', 'Porvenir'),
    ('Primavera', 'Primavera'),
    ('Timaukel', 'Timaukel'),
    ('Natales', 'Natales'),
    ('Torres del Paine', 'Torres del Paine'),
    ('Santiago', 'Santiago'),
    ('Cerrillos', 'Cerrillos'),
    ('Cerro Navia', 'Cerro Navia'),
    ('Conchalí', 'Conchalí'),
    ('El Bosque', 'El Bosque'),
    ('Estación Central', 'Estación Central'),
    ('Huechuraba', 'Huechuraba'),
    ('Independencia', 'Independencia'),
    ('La Cisterna', 'La Cisterna'),
    ('La Florida', 'La Florida'),
    ('La Granja', 'La Granja'),
    ('La Pintana', 'La Pintana'),
    ('La Reina', 'La Reina'),
    ('Las Condes', 'Las Condes'),
    ('Lo Barnechea', 'Lo Barnechea'),
    ('Lo Espejo', 'Lo Espejo'),
    ('Lo Prado', 'Lo Prado'),
    ('Macul', 'Macul'),
    ('Maipú', 'Maipú'),
    ('Ñuñoa', 'Ñuñoa'),
    ('Pedro Aguirre Cerda', 'Pedro Aguirre Cerda'),
    ('Peñalolén', 'Peñalolén'),
    ('Providencia', 'Providencia'),
    ('Pudahuel', 'Pudahuel'),
    ('Quilicura', 'Quilicura'),
    ('Quinta Normal', 'Quinta Normal'),
    ('Recoleta', 'Recoleta'),
    ('Renca', 'Renca'),
    ('San Joaquín', 'San Joaquín'),
    ('San Miguel', 'San Miguel'),
    ('San Ramón', 'San Ramón'),
    ('Vitacura', 'Vitacura'),
    ('Puente Alto', 'Puente Alto'),
    ('Pirque', 'Pirque'),
    ('San José de Maipo', 'San José de Maipo'),
    ('Colina', 'Colina'),
    ('Lampa', 'Lampa'),
    ('Tiltil', 'Tiltil'),
    ('San Bernardo', 'San Bernardo'),
    ('Buin', 'Buin'),
    ('Calera de Tango', 'Calera de Tango'),
    ('Paine', 'Paine'),
    ('Melipilla', 'Melipilla'),
    ('Alhué', 'Alhué'),
    ('Curacaví', 'Curacaví'),
    ('María Pinto', 'María Pinto'),
    ('San Pedro', 'San Pedro'),
    ('Talagante', 'Talagante'),
    ('El Monte', 'El Monte'),
    ('Isla de Maipo', 'Isla de Maipo'),
    ('Padre Hurtado', 'Padre Hurtado'),
    ('Peñaflor', 'Peñaflor'),
)

COMMUNE_REGIONS = {
    "Arica": "XV",
    "Camarones": "XV",
    "Putre": "XV",
    "General Lagos": "XV",
    "Iquique": "I",
    "Alto Hospicio": "I",
    "Pozo Almonte": "I",
    "Camiña": "I",
    "Colchane": "I",
    "Huara": "I",
    "Pica": "I",
    "Antofagasta": "II",
    "Mejillones": "II",
    "Sierra Gorda": "II",
    "Taltal": "II",
    "Calama": "II",
    "Ollagüe": "II",
    "San Pedro de Atacama": "II",
    "Tocopilla": "II",
    "María Elena": "II",
    "Copiapó": "III",
    "Caldera": "III",
    "Tierra Amarilla": "III",
    "Chañaral": "III",
    "Diego de Almagro": "III",
    "Vallenar": "III",
    "Alto del Carmen": "III",
    "Freirina": "III",
    "Huasco": "III",
    "La Serena": "IV",
    "Coquimbo": "IV",
    "Andacollo": "IV",
    "La Higuera": "IV",
    "Paiguano": "IV",
    "Vicuña": "IV",
    "Illapel": "IV",
    "Canela": "IV",
    "Los Vilos": "IV",
    "Salamanca": "IV",
    "Ovalle": "IV",
    "Combarbalá": "IV",
    "Monte Patria": "IV",
    "Punitaqui": "IV",
    "Río Hurtado": "IV",
    "Valparaíso": "V",
    "Casablanca": "V",
    "Concón": "V",
    "Juan Fernández": "V",
    "Puchuncaví": "V",
    "Quintero": "V",
    "Viña del Mar": "V",
    "Isla de Pascua": "V",
    "Los Andes": "V",
    "Calle Larga": "V",
    "Rinconada": "V",
    "San Esteban": "V",
    "La Ligua": "V",
    "Cabildo": "V",
    "Papudo": "V",
    "Petorca": "V",
    "Zapallar": "V",
    "Quillota": "V",
    "Calera": "V",
    "Hijuelas": "V",
    "La Cruz": "V",
    "Nogales": "V",
    "San Antonio": "V",
    "Algarrobo": "V",
    "Cartagena": "V",
    "El Quisco": "V",
    "El Tabo": "V",
    "Santo Domingo": "V",
    "San Felipe": "V",
    "Catemu": "V",
    "Llaillay": "V",
    "Panquehue": "V",
    "Putaendo": "V",
    "Santa María": "V",
    "Quilpué": "V",
    "Limache": "V",
    "Olmué": "V",
    "Villa Alemana": "V",
    "Rancagua": "VI",
    "Codegua": "VI",
    "Coinco": "VI",
    "Coltauco": "VI",
    "Doñihue": "VI",
    "Graneros": "VI",
    "Las Cabras": "VI",
    "Machalí": "VI",
    "Malloa": "VI",
    "Mostazal": "VI",
    "Olivar": "VI",
    "Peumo": "VI",
    "Pichidegua": "VI",
    "Quinta de Tilcoco": "VI",
    "Rengo": "VI",
    "Requínoa": "VI",
    "San Vicente": "VI",
    "Pichilemu": "VI",
    "La Estrella": "VI",
    "Litueche": "VI",
    "Marchihue": "VI",
    "Navidad": "VI",
    "Paredones": "VI",
    "San Fernando": "VI",
    "Chépica": "VI",
    "Chimbarongo": "VI",
    "Lolol": "VI",
    "Nancagua": "VI",
    "Palmilla": "VI",
    "Peralillo": "VI",
    "Placilla": "VI",
    "Pumanque": "VI",
    "Santa Cruz": "VI",
    "Talca": "VII",
    "Constitución": "VII",
    "Curepto": "VII",
    "Empedrado": "VII",
    "Maule": "VII",
    "Pelarco": "VII",
    "Pencahue": "VII",
    "Río Claro": "VII",
    "San Clemente": "VII",
    "San Rafael": "VII",
    "Cauquenes": "VII",
    "Chanco": "VII",
    "Pelluhue": "VII",
    "Curicó": "VII",
    "Hualañé": "VII",
    "Licantén": "VII",
    "Molina": "VII",
    "Rauco": "VII",
    "Romeral": "VII",
    "Sagrada Familia": "VII",
    "Teno": "VII",
    "Vichuquén": "VII",
    "Linares": "VII",
    "Colbún": "VII",
    "Longaví": "VII",
    "Parral": "VII",
    "Retiro": "VII",
    "San Javier": "VII",
    "Villa Alegre": "VII",
    "Yerbas Buenas": "VII",
    "Concepción": "VIII",
    "Coronel": "VIII",
    "Chiguayante": "VIII",
    "Florida": "VIII",
    "Hualqui": "VIII",
    "Lota": "VIII",
    "Penco": "VIII",
    "San Pedro de La Paz": "VIII",
    "Santa Juana": "VIII",
    "Talcahuano": "VIII",
    "Tomé": "VIII",
    "Hualpén": "VIII",
    "Lebu": "VIII",
    "Arauco": "VIII",
    "Cañete": "VIII",
    "Contulmo": "VIII",
    "Curanilahue": "VIII",
    "Los Álamos": "VIII",
    "Tirúa": "VIII",
    "Los Ángeles": "VIII",
    "Antuco": "VIII",
    "Cabrero": "VIII",
    "Laja": "VIII",
    "Mulchén": "VIII",
    "Nacimiento": "VIII",
    "Negrete": "VIII",
    "Quilaco": "VIII",
    "Quilleco": "VIII",
    "San Rosendo": "VIII",
    "Santa Bárbara": "VIII",
    "Tucapel": "VIII",
    "Yumbel": "VIII",
    "Alto Biobío": "VIII",
    "Chillán": "VIII",
    "Bulnes": "VIII",
    "Cobquecura": "VIII",
    "Coelemu": "VIII",
    "Coihueco": "VIII",
    "Chillán Viejo": "VIII",
    "El Carmen": "VIII",
    "Ninhue": "VIII",
    "Ñiquén": "VIII",
    "Pemuco": "VIII",
    "Pinto": "VIII",
    "Portezuelo": "VIII",
    "Quillón": "VIII",
    "Quirihue": "VIII",
    "Ránquil": "VIII",
    "San Carlos": "VIII",
    "San Fabián": "VIII",
    "San Ignacio": "VIII",
    "San Nicolás": "VIII",
    "Treguaco": "VIII",
    "Yungay": "VIII",
    "Temuco": "IX",
    "Carahue": "IX",
    "Cunco": "IX",
    "Curarrehue": "IX",
    "Freire": "IX",
    "Galvarino": "IX",
    "Gorbea": "IX",
    "Lautaro": "IX",
    "Loncoche": "IX",
    "Melipeuco": "IX",
    "Nueva Imperial": "IX",
    "Padre Las Casas": "IX",
    "Perquenco": "IX",
    "Pitrufquén": "IX",
    "Pucón": "IX",
    "Saavedra": "IX",
    "Teodoro Schmidt": "IX",
    "Toltén": "IX",
    "Vilcún": "IX",
    "Villarrica": "IX",
    "Cholchol": "IX",
    "Angol": "IX",
    "Collipulli": "IX",
    "Curacautín": "IX",
    "Ercilla": "IX",
    "Lonquimay": "IX",
    "Los Sauces": "IX",
    "Lumaco": "IX",
    "Purén": "IX",
    "Renaico": "IX",
    "Traiguén": "IX",
    "Victoria": "IX",
    "Valdivia": "XIV",
    "Corral": "XIV",
    "Lanco": "XIV",
    "Los Lagos": "XIV",
    "Máfil": "XIV",
    "Mariquina": "XIV",
    "Paillaco": "XIV",
    "Panguipulli": "XIV",
    "La Unión": "XIV",
    "Futrono": "XIV",
    "Lago Ranco": "XIV",
    "Río Bueno": "XIV",
    "Puerto Montt": "X",
    "Calbuco": "X",
    "Cochamó": "X",
    "Fresia": "X",
    "Frutillar": "X",
    "Los Muermos": "X",
    "Llanquihue": "X",
    "Maullín": "X",
    "Puerto Varas": "X",
    "Castro": "X",
    "Ancud": "X",
    "Chonchi": "X",
    "Curaco de Vélez": "X",
    "Dalcahue": "X",
    "Puqueldón": "X",
    "Queilén": "X",
    "Quellón": "X",
    "Quemchi": "X",
    "Quinchao": "X",
    "Osorno": "X",
    "Puerto Octay": "X",
    "Purranque": "X",
    "Puyehue": "X",
    "Río Negro": "X",
    "San Juan de la Costa": "X",
    "San Pablo": "X",
    "Chaitén": "X",
    "Futaleufú": "X",
    "Hualaihué": "X",
    "Palena": "X",
    "Coyhaique": "XI",
    "Lago Verde": "XI",
    "Aysén": "XI",
    "Cisnes": "XI",
    "Guaitecas": "XI",
    "Cochrane": "XI",
    "O'Higgins": "XI",
    "Tortel": "XI",
    "Chile Chico": "XI",
    "Río Ibáñez": "XI",
    "Punta Arenas": "XII",
    "Laguna Blanca": "XII",
    "Río Verde": "XII",
    "San Gregorio": "XII",
    "Cabo de Hornos": "XII",
    "Antártica": "XII",
    "Porvenir": "XII",
    "Primavera": "XII",
    "Timaukel": "XII",
    "Natales": "XII",
    "Torres del Paine": "XII",
    "Santiago": "RM",
    "Cerrillos": "RM",
    "Cerro Navia": "RM",
    "Conchalí": "RM",
    "El Bosque": "RM",
    "Estación Central": "RM",
    "Huechuraba": "RM",
    "Independencia": "RM",
    "La Cisterna": "RM",
    "La Florida": "RM",
    "La Granja": "RM",
    "La Pintana": "RM",
    "La Reina": "RM",
    "Las Condes": "RM",
    "Lo Barnechea": "RM",
    "Lo Espejo": "RM",
    "Lo Prado": "RM",
    "Macul": "RM",
    "Maipú": "RM",
    "Ñuñoa": "RM",
    "Pedro Aguirre Cerda": "RM",
    "Peñalolén": "RM",
    "Providencia": "RM",
    "Pudahuel": "RM",
    "Quilicura": "RM",
    "Quinta Normal": "RM",
    "Recoleta": "RM",
    "Renca": "RM",
    "San Joaquín": "RM",
    "San Miguel": "RM",
    "San Ramón": "RM",
    "Vitacura": "RM",
    "Puente Alto": "RM",
    "Pirque": "RM",
    "San José de Maipo": "RM",
    "Colina": "RM",
    "Lampa": "RM",
    "Tiltil": "RM",
    "San Bernardo": "RM",
    "Buin": "RM",
    "Calera de Tango": "RM",
    "Paine": "RM",
    "Melipilla": "RM",
    "Alhué": "RM",
    "Curacaví": "RM",
    "María Pinto": "RM",
    "San Pedro": "RM",
    "Talagante": "RM",
    "El Monte": "RM",
    "Isla de Maipo": "RM",
    "Padre Hurtado": "RM",
    "Peñaflor": "RM",
}
