from django.utils.translation import gettext_lazy as _
# source of cities and towns
# https://www.britannica.com/topic/list-of-cities-and-towns-in-Israel-2060226

CITIES_CHOICES = (
    ('AF', _('\'Afula')),
    ('AK', _('\'Akko')),
    ('AR', _('\'Arad')),
    ('AS', _('Ashdod')),
    ('AQ', _('Ashqelon')),
    ('BY', _('Bat Yam')),
    ('BE', _('Beersheba')),
    ('BS', _('Bet Sheʾan')),
    ('BR', _('Bet Sheʿarim')),
    ('BN', _('Bnei Brak')),
    ('CA', _('Caesarea')),
    ('DI', _('Dimona')),
    ('DO', _('Dor')),
    ('EL', _('Elat')),
    ('EN', _('ʿEn Gedi')),
    ('GI', _('Givʿatayim')),
    ('HA', _('H̱adera')),
    ('HF', _('Haifa')),
    ('HE', _('Herzliyya')),
    ('HO', _('H̱olon')),
    ('JE', _('Jerusalem')),
    ('KA', _('Karmiʾel')),
    ('KE', _('Kefar Sava')),
    ('LO', _('Lod')),
    ('ME', _('Meron')),
    ('NA', _('Nahariyya')),
    ('NZ', _('Nazareth')),
    ('NE', _('Netanya')),
    ('PE', _('Petaẖ Tiqwa')),
    ('QI', _('Qiryat Shemona')),
    ('RA', _('Ramat Gan')),
    ('RL', _('Ramla')),
    ('RE', _('Reẖovot')),
    ('RI', _('Rishon LeẔiyyon')),
    ('SE', _('Sedom')),
    ('TE', _('Tel Aviv–Yafo')),
    ('TI', _('Tiberias')),
    ('ZE', _('Ẕefat')),
)
